name: 01 - BuildingBlocks
on:
  push: 
    branches:
      - main
jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "hello world"
  echo-goodBye:
    runs-on: ubuntu-latest
    steps:
      - name: SayGoodBye
        run: |
          # Your commands here